version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__Default=Host=db;Database=BookEasyDB;Username=postgres;Password=password
      - JWT__Secret=super_secret_key_12345!
      - JWT__ValidIssuer=bookeasy-api
      - JWT__ValidAudience=bookeasy-angular
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=BookEasyDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: